-- INSERT INTO colors (color, min, max) VALUES ('Currant', 121, 1000);
--
-- INSERT INTO colors (color, min, max) VALUES ('Garnet', 116, 120);
--
-- INSERT INTO colors (color, min, max) VALUES ('Rooibos', 111, 115);
--
-- INSERT INTO colors (color, min, max) VALUES ('Hollyberry', 106, 110);
--
-- INSERT INTO colors (color, min, max) VALUES ('Firecracker', 101, 105);
--
-- INSERT INTO colors (color, min, max) VALUES ('Cranberry', 96, 100);
--
-- INSERT INTO colors (color, min, max) VALUES ('Red', 91, 95);
--
-- INSERT INTO colors (color, min, max) VALUES ('Victorian', 86, 90);
--
-- INSERT INTO colors (color, min, max) VALUES ('Papaya', 81, 85);
--
-- INSERT INTO colors (color, min, max) VALUES ('Orange', 76, 80);
--
-- INSERT INTO colors (color, min, max) VALUES ('Conch', 71, 75);
--
-- INSERT INTO colors (color, min, max) VALUES ('Caution', 66, 70);
--
-- INSERT INTO colors (color, min, max) VALUES ('Semolina', 61, 65);
--
-- INSERT INTO colors (color, min, max) VALUES ('Creme Brulee', 56, 60);
--
-- INSERT INTO colors (color, min, max) VALUES ('Green Tea', 51, 55);
--
-- INSERT INTO colors (color, min, max) VALUES ('Peapod', 46, 50);
--
-- INSERT INTO colors (color, min, max) VALUES ('Grass', 41, 45);
--
-- INSERT INTO colors (color, min, max) VALUES ('Everglade', 36, 40);
--
-- INSERT INTO colors (color, min, max) VALUES ('Tranquil', 31, 35);
--
-- INSERT INTO colors (color, min, max) VALUES ('Calypso', 26, 30);
--
-- INSERT INTO colors (color, min, max) VALUES ('Whirlpool', 21, 25);
--
-- INSERT INTO colors (color, min, max) VALUES ('Baltic', 16, 20);
--
-- INSERT INTO colors (color, min, max) VALUES ('Fjord', 11, 15);
--
-- INSERT INTO colors (color, min, max) VALUES ('Ciel', 6, 10);
--
-- INSERT INTO colors (color, min, max) VALUES ('Celestial', 1, 5);
--
-- INSERT INTO colors (color, min, max) VALUES ('Sapphire', -4, 0);
--
-- INSERT INTO colors (color, min, max) VALUES ('Solstice', -9, -5);
--
-- INSERT INTO colors (color, min, max) VALUES ('Lullaby', -14, -10);
--
-- INSERT INTO colors (color, min, max) VALUES ('Amethyst', -19, -15);
--
-- INSERT INTO colors (color, min, max) VALUES ('Indigo', -24, -20);
--
-- INSERT INTO colors (color, min, max) VALUES ('Blackberry', -29, -25);
--
-- INSERT INTO colors (color, min, max) VALUES ('Coal', -1000, -30);
